<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org"
         xmlns:xsi="http://w3.org"
         xsi:schemaLocation="http://apache.org http://apache.org">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.mine</groupId>
    <artifactId>shop</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Локальное подключение скачанного файла внутри репозитория -->
        <dependency>
            <groupId>destroystokyo.cardboard</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.16.5-R0.1-LOCAL</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/paper-api.jar</systemPath>
        </dependency>
    </dependencies>

    <build>
        <finalName>MineShop</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>
