name: Build MineShop

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Create libs folder and download Paper API
      run: |
        mkdir -p FrostAurs/libs
        curl -L -o FrostAurs/libs/paper-api.jar https://papermc.io

    - name: Build with Maven
      run: mvn -B package --file FrostAurs/pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MineShop-Plugin
        path: FrostAurs/target/*.jar
